services:
  - docker

before_install:
  # Build
  - docker-compose -f docker-compose-build.yaml build --parallel

  # Tagging
  - docker tag udagram-api-feed gabrielssc/udagram-api-feed:v1
  - docker tag udagram-api-user gabrielssc/udagram-api-user:v1
  - docker tag udagram-frontend gabrielssc/udagram-frontend:v1
  - docker tag udagram-reverseproxy gabrielssc/udagram-reverseproxy:v1

  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gabrielssc/udagram-api-feed:v1
  - docker push gabrielssc/udagram-api-user:v1
  - docker push gabrielssc/udagram-frontend:v1
  - docker push gabrielssc/udagram-reverseproxy:v1
